config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'missions_recruteur', to: 'pages#missions_recruteur'
  get 'missions_mes_codeurs', to: 'pages#missions_mes_codeurs'
  get 'about', to: 'pages#about'

  resources :users, only: [:edit, :update] do
    resources :coders, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :coders, only: [:index, :show, :edit, :update] do
    resources :missions, only: [:new, :create]
  end
  resources :missions, only: [:index, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end
  get 'missions/:id/accept', to: 'missions#accept', as: :mission_accept
  get 'missions/:id/reject', to: 'missions#reject', as: :mission_reject
  resources :reviews, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coder.rb
class Coder < ApplicationRecord

CODE_LIST = [ "Ruby", "Python", "Javascript", "HTML", "CSS", "ReactJS", "VueJS", "API", "PHP", "Java", "Symfony" ]

  belongs_to :user
  has_many :missions
  has_many :reviews, through: :missions
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :price_per_day, presence: true, inclusion: { in: (1..10_000) }
  validates :email, format: { with: /\A([^@]+)@([^@]+)\.(\w+)\z/, message: "email valide uniquement" }
  validates :phone_number, presence: true
  validates :phone_number, format: { with: /\A(0|\+33[\s-]?)[1-9][\s-]?(\d{2}[\s-]?){4}\z/, message: "uniquement + ou des nombres" }
  validates :description,  length: { minimum: 10 }

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :description ],
    associated_against: {
      missions: [ :title, :description ]
    },
    using: {
      tsearch: { prefix: true }
    }

  acts_as_taggable_on :tags

end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user
  belongs_to :coder
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  # validates :start_date, presence: true
  # validates :end_date, presence: true, date: { after_or_equal_to: :start_date }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :mission

  validates :content, presence: true
  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :coders
  has_many :missions
  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :phone_number, format: { with: /\A(0|\+33[\s-]?)[1-9][\s-]?(\d{2}[\s-]?){4}\z/, message: "uniquement + ou des nombres" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

  # For additional in app/views/devise/registrations/edit.html.erb
  devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/coders_controller.rb
class CodersController < ApplicationController
  before_action :set_coder, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:query].present?
      @query = params[:query]

      @coders = policy_scope(Coder.global_search(@query))
    else
      @coders = policy_scope(Coder.all)
    end
    @coders = @coders.tagged_with(params[:tag]) if params[:tag].present?
  end

  def show
  end

  def new
    @coder = Coder.new
    authorize @coder
  end

  def create
    @coder = Coder.new(coder_params)
    @user = User.find(params[:user_id])
    @coder.user = @user
    authorize @coder
    if @coder.save
      redirect_to coder_path(@coder)
    else
      render 'new'
    end
  end

  def edit
    authorize @coder
  end

  def update
    @coder.update(coder_params)
    authorize @coder
    redirect_to coder_path(@coder)
  end

def tagged
  if params[:tag].present?
    @coders = policy_scope(Coders.tagged_with(params[:tag]))
  else
  render :index
  end
end

  private

  def coder_params
    params.require(:coder).permit(:name, :price_per_day, :email, :phone_number, :description, :photo, tag_list: [])
  end

  def set_coder
    @coder = Coder.find(params[:id])
    authorize @coder
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_mission, only: [:accept, :reject]

  def index
    @missions = policy_scope(Mission.all)
  end

  def new
    @mission = Mission.new
    @coder = Coder.find(params[:coder_id])
    @mission.coder = @coder
    authorize @coder
  end

  def create
    @mission = Mission.new(mission_params)
    @coder = Coder.find(params[:coder_id])
    @mission.coder = @coder
    duration = @mission.end_date - @mission.start_date
    @mission.total_price = duration * @coder.price_per_day
    @mission.user = current_user
    # @mission.validated_mission = true
    authorize @mission
    if @mission.save
      redirect_to "/missions_recruteur"
    else
      render 'new'
    end
  end

  def accept
    @mission.validated_mission = true
    @mission.save
    redirect_to "/missions_mes_codeurs"
  end

  def reject
    @mission.validated_mission = false
    @mission.save
    redirect_to "/missions_mes_codeurs"
  end

  private

  def mission_params
    params.require(:mission).permit(:start_date, :end_date, :total_price, :validated_mission, :title, :description)
  end

  def set_mission
    @mission = Mission.find(params[:id])
    authorize @mission
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about]

  def home
  end

  def about
  end

  def dashboard
  end

  def missions_mes_codeurs
  end

  def missions_recruteur
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_mission, only: [:new, :create]

  def index
    @reviews = policy_scope(Review.all)
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.mission = @mission
    authorize @review
    if @review.save
      redirect_to coder_path(@mission.coder) # vers la show du nesting model
    else
      render :new
    end
  end

  # def edit
  # end

  # def update
  #   @review.update(review_params)
  #   redirect_to review_path(@review) # vers la show
  # end

  def destroy
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
    authorize @review
  end

  def set_mission
    @mission = Mission.find(params[:mission_id])
    authorize @mission
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to "/dashboard"
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :company_name, :photo)
  end

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coders/_coder_card.html.erb
<div class="coder-card">
  <div class="coder-card-price">
    <span><%= coder.price_per_day%> €/j</span>
  </div>

  <% if coder.reviews.count > 0 %>
    <div class="coder-card-review">
      <span><i class="fas fa-star"></i> <%= (coder.reviews.sum(:rating) / coder.reviews.count.to_f).round(1)%></span>
    </div>
  <% end %>
  <%= link_to coder_path(coder) do %>
  <% if coder.photo.attached? %>
    <div class="coder-card-image" style="background-image: url('<%= cl_image_path coder.photo.key, height: 300, width: 400, crop: :fill, gravity: :face %>')"></div>
  <% else %>
    <div class="coder-card-image" style="background-image: url(https://res.cloudinary.com/dnpdonlro/image/upload/v1605711952/committed_to_excellence-8c514667b11ec04b4172d45d04718e4968c6a518875df69fa7faad1fc956a4e9_hvctwi.jpg)"></div>
  <% end %>
  <% end %>
  <div class="coder-card-content">
    <div class="coder-card-title">
      <h4><%= coder.name %></h4>
    </div>
    <div class="coder-card-description">
      <p><%= coder.description.truncate(50) %></p>
    </div>
    <div class="coder-card-tags d-flex">
      <% coder.tag_list.first(4).each do |tag| %>
        <div class="coder-tags"><%= tag %></div>
      <% end %>
    </div>
  </div>
  <div class="coder-card-actions">
    <%= link_to 'En savoir plus', coder_path(coder), class: "btn btn-outline-primary rounded-pill" %>
    <% if coder.user == current_user %>
      <span class="coder-card-appartenance"> Mon profil </span>
    <% end %>
  </div>
</div>

app/views/coders/index.html.erb
<br>
<h2>Trouver votre expert parmi nos freelances!!</h2>
<%= simple_form_for :query, url: coders_path, method: :get do |f| %>
  <div class="row justify-content-center">
    <div class="search-form-control form-group">
      <input class="form-control string required" placeholder="Essayer 'React.js','java', 'Steve Jobs'..." type="text" name="query" id="query" value="<%= params[:query] %>"/>
        <button name="button" type="submit" class="rounded-pill btn btn-danger">
          <i class="fas fa-search"></i>  Chercher
        </button>
        <div class="tag">

            <% Coder::CODE_LIST.each do |tag| %>
              <%= link_to tag, coders_path(tag: tag) %>
            <% end %>

        </div>
    </div>
  </div>
<% end %>


 <div class="container mt-3">
  <div class="row">
    <div class="col-12">
    </div>
    </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>Vous avez cherché "<strong><%= @query %></strong>". Nous avons trouvé <%= @coders.count %> codeurs sur  <%= Coder.count %> sur notre site web.</p>
      <% else %>
        <p><%= Coder.count %> Codeurs trouvés.</p>
        <p class="btn btn-outline-primary rounded-pill">
            <%= link_to "Afficher tous les codeurs", coders_path %>

      <% end %>

    </div>
  </div>
  <div class="row">
    <% @coders.order(updated_at: :desc ).each do |coder| %>
      <div class="col-4">
        <%= render partial: 'coders/coder_card', locals: {coder: coder} %>
      </div>
    <% end %>
  </div>
</div>

app/views/coders/show.html.erb
<br>
<div class="back-bar">
<%= link_to " << Voir tous les codeurs", _back_url, class: "btn btn-outline-danger rounded-pill"  %>
</div>

<div class="container">
  <div class="show-top-infos flex-between">
    <div class="coder-picture p-3 d-flex">
      <% if @coder.photo.attached? %>
        <%= cl_image_tag @coder.photo.key, width: 300, crop: :fill, gravity: :face, class: "avatar-big" %>
      <% else %>
        <%= image_tag "https://res.cloudinary.com/dnpdonlro/image/upload/v1605711897/qfp8ofi6fmh2nrgx88xr5cwi2jl9.jpg", height: 200, weight: 300, class: "profil-picture" %>
      <% end %>
    </div>
    <div class="name-tags">
      <h1 class="m-0"><%= @coder.name %></h1>
      <br>
      <span><%= @coder.email %></span>
    </div>
    <div class="cta-show">
      <% if current_user == @coder.user %>
        <%= link_to "Editer mon profil", edit_coder_path(@coder), class: "btn btn-danger rounded-pill" %>
      <% else %>
          <%= link_to "Lui confier une mission", new_coder_mission_path(@coder), class: "btn btn-danger rounded-pill" %>
      <% end %>
    </div>
  </div>
  <div class="show-stats">
    <div class="coder-stats d-flex justify-content-between">
      <div class="coder-stats-box d-flex justify-content-center align-items-center">
        <span><%= @coder.price_per_day %> € / jour</span>
      </div>
      <% nb_missions_ok = @coder.missions.where(validated_mission: true).count %>
      <div class="coder-stats-box d-flex justify-content-center align-items-center">
        <% if nb_missions_ok == 0 %>
          <span>Disponible pour vos missions</span>
        <% elsif nb_missions_ok == 0 %>
          <span>1 mission acceptée</span>
        <% else %>
          <span><%= nb_missions_ok %> missions acceptées</span>
        <% end %>
      </div>
      <% if @coder.reviews.count > 0 %>
        <div class="coder-stats-box d-flex justify-content-center align-items-center">
          <span><%= (@coder.reviews.sum(:rating) / @coder.reviews.count.to_f).round(1)%> <i class="fas fa-star"></i></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">

  <div class="row my-4">
    <div class="col-12">
      <div class="show-tags d-flex">
        <% @coder.tag_list.each do |tag| %>
          <div class="coder-tags"><%= tag %></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row my-4">
    <div class="col-12">
      <div class="description-coder">
        <h3><%= @coder.name %> en quelques mots</h3>
        <p><%= @coder.description%></p>
      </div>
    </div>
  </div>

  <% if nb_missions_ok > 0 %>
    <div class="mes-missions">
      <div class="row my-4">
        <div class="col-offset-1 coder-missions-box">
          <h3 class="m-4">Missions acceptées :</h3>
          <ul class= "missions-list">
            <% sorted_missions = @coder.missions.where(validated_mission: true).order(start_date: :desc) %>
            <% sorted_missions.each do |mission| %>
              <li>
                <%= render partial: 'missions/mission_card', locals: {mission: mission} %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/missions/_mission_card.html.erb
<div class="mission-card">
  <div class="mission-top flex-between">
    <h5><%= mission.title %></h5>
    <span><i class="far fa-calendar-alt mr-2"></i>du <%= mission.start_date %> au <%= mission.end_date %></span>
  </div>
  <hr class="m-1">
  <div class="mission-long-desc mt-2">
    <p><%= mission.description %></p>
  </div>

  <% if mission.coder.user == current_user %>
    <hr class="m-1">
    <div id="missions-confidentials-coder-infos" class="missions-confidentials-box">
      <div class="mission-infos-box flex-center pl-0">
        <span>Détails mission </span>
      </div>
      <div class="mission-infos-box flex-center">
        <span><small>Budget: </small><%= mission.total_price %> €</span>
      </div>
      <div class="mission-infos-box flex-between">
        <div class="pr-3">
        <% if mission.validated_mission %>
          <span><small> Statut: </small>Validée</span>
        <% elsif mission.validated_mission.nil? %>
          <span><small> Statut: </small>En attente</span>
        <% else %>
          <span><small> Statut: </small>Refusée</span>
        <% end %>
        </div>
        <div>
          <%= link_to "Accepter", mission_accept_path(mission), class: "btn btn-primary" %>
          <%= link_to "Refuser", mission_reject_path(mission), class: "btn btn-danger" %>
        </div>
      </div>
      <div class="mission-infos-box flex-between">
        <div class="flex-center pr-3">
          <% if mission.user.photo.attached? %>
            <%= cl_image_tag mission.user.photo.key , height: 40, weight: 40,
            class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dnpdonlro/image/upload/v1605793441/unknown_user_smsl6v.jpg", height: 40, weight: 40,
            class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
        </div>
        <div>
          <span><small> Recruteur: </small><%= mission.user.first_name %> <%= mission.user.last_name %></span>
          <br>
          <% if !mission.user.company_name.blank? %>
          <span><small> Société: </small><%= mission.user.company_name %></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>


  <% if mission.user == current_user %>
    <hr class="m-1">
    <div id="missions-confidentials-recruiter-infos" class="missions-confidentials-box">
      <div class="mission-infos-box flex-center pl-0">
        <span>Détails mission </span>
      </div>
      <div class="mission-infos-box flex-center">
        <span><small>Budget: </small><%= mission.total_price %> €</span>
      </div>
      <div class="mission-infos-box flex-center">
        <% if mission.validated_mission %>
          <span><small> Statut: </small>Validée</span>
        <% elsif mission.validated_mission.nil? %>
          <span><small> Statut: </small>En attente</span>
        <% else %>
          <span><small> Statut: </small>Refusée</span>
        <% end %>
      </div>
      <div class="mission-infos-box flex-between">
        <div class="flex-center pr-3">
          <% if mission.coder.photo.attached? %>
            <%= cl_image_tag mission.coder.photo.key , height: 40, weight: 40,
            class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dnpdonlro/image/upload/v1605793441/unknown_user_smsl6v.jpg", height: 40, weight: 40,
            class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
        </div>
        <div>
          <span><small> Codeur: </small>
            <%= link_to coder_path(mission.coder) do %>
              <%= mission.coder.name %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
  <% end %>

  <% if mission.reviews.count == 0 %>
    <% if mission.user == current_user %>
      <hr class="m-1">
      <div id="missions-review-infos">
        <%= link_to "Ajouter un avis", new_mission_review_path(mission)  %>
      </div>
    <% end %>
  <% else %>
    <hr class="m-1">
    <div class="missions-review-infos">
      <div class="stars-review">
        <span class="">
          <% counter = 0 %>
          <% 5.times do %>
            <i class="<%= mission.reviews.first.rating > counter ? 'fas fa-star' : 'far fa-star' %>"></i>
            <% counter += 1 %>
          <% end %>
        </span>
      </div>
      <div>
        <p><em>"<%= mission.reviews.first.content %>"</em></p>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <br>
      <h2>Bienvenue sur ton espace <%= current_user.first_name %></h2>
      <hr>

   <!--    DASHBOARD  -->

      <div class="dash">
        <div class="compte">
          <br>
          <span><%= cl_image_tag current_user.photo.key , height: 70, weight: 70, class: "avatar-bordered" %></span>
          <%= current_user.first_name %> <%= current_user.last_name %>
          <br>
          <br>
          <p><i class="fas fa-envelope-open-text"></i>   <%= current_user.email %></p>
          <p><i class="fas fa-phone-square-alt"></i>   <%= current_user.phone_number %></p>
          <p><i class="fas fa-building"></i>   <%= current_user.company_name %></p>
        </div>
        <div class="board">
          <br>
          <h3>Mes statistiques :</h3>
          <div class="d-flex">
            <div class="px-2">
              <p> Missions données (nombre) : <%= current_user.missions.count %></p>
              <p> Missions données (euros) : <%= current_user.missions.sum(:total_price) %> €</p>
            </div>
            <div class="px-2">
              <% number_accepted_missions = 0 %>
              <% number_pending_missions = 0 %>
              <% amount_accepted_missions = 0 %>
              <% current_user.coders.each do |coder|  %>
                <% number_accepted_missions += coder.missions.where(validated_mission: true).count %>
                <% number_accepted_missions += coder.missions.where(validated_mission: nil).count %>
                <% amount_accepted_missions += coder.missions.where(validated_mission: true).sum(:total_price) %>
              <% end %>
              <p> Missions en attente (nombre) : <%= number_pending_missions %></p>
              <p> Missions acceptées (nombre) : <%= number_accepted_missions %></p>
              <p> Missions acceptées (euros) : <%= amount_accepted_missions %> €</p>
            </div>
          </div>
        </div>
      </div>

      <div class="dashboard-coder">
        <div class="card-category" style="background-image: url(https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60)">
          Espace recruteur
        </div>
        <br>
        <div class="company flex-vert-around">
          <h3><%= link_to "Mes missions", "/missions_recruteur" %></h3>
          <h3><%= link_to "Mes freelances favoris", "#" %></h3>
        </div>
        <hr>
      </div>
      <br>
      <div class="row">
        <% mes_codeurs_en_mission = [] %>
        <% current_user.missions.each do |mission| %>
          <% mes_codeurs_en_mission << mission.coder %>
        <% end %>
        <% mes_codeurs_en_mission.uniq.each do |coder| %>
          <div class="col-4">
            <%= render partial: 'coders/coder_card', locals: {coder: coder} %>
          </div>
        <% end %>
      </div>
<!--       ESPACE RECRUTEUR / CODEUR  -->

      <div class="dashboard-coder">
        <div class="card-category" style="background-image: url(https://images.unsplash.com/photo-1550439062-609e1531270e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60)">
          Espace codeur
        </div>
        <br>
        <div class="coder flex-vert-around">
          <% if current_user.coders.count == 0 %>
            <%= link_to "Créer mon profil de codeur", new_user_coder_path(current_user)%>
          <% elsif current_user.coders.count == 1 %>
            <h3><%= link_to "Editer mon profil de codeur", "#"%></h3>
            <h3><%= link_to "Voir mes missions de codeur", missions_mes_codeurs_path%></h3>
            <h3><%= link_to "Créer un autre profil de codeur", new_user_coder_path(current_user)%></h3>
          <% else %>
            <h3><%= link_to "Créer un profil de codeur", new_user_coder_path(current_user)%></h3>
            <h3><%= link_to "Voir les missions de mes codeurs", missions_mes_codeurs_path%></h3>
          <% end %>
        </div>
      </div>
      <br>
      <div class="row">
        <% current_user.coders.each do |coder| %>
          <div class="col-4">
            <%= render partial: 'coders/coder_card', locals: {coder: coder} %>
          </div>
        <% end %>
      </div>
      <br>
 <!--        ESPACE RECRUTEUR  -->

    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2>Donnez votre avis sur la mission </h2>
      <p> Mission : <%= @mission.title %> confiée à <%= @mission.coder.name %></p>
      <%= simple_form_for [@mission, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<div>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="icon">
    <li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
    <li><a href="#" target="_blank"><i class="fab fa-github"></i></a></li>
    <li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
    <li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
  </ul>
   <p> <%= link_to "Notre Mission", about_path %> </p>
  <p>Ce site internet a été fait avec 🍺 au Wagon et depuis chez nous </p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dnpdonlro/image/upload/v1605794291/freewagoners_olzeyc.png", height: 50 %>
    <%# if !user_signed_in? %>
<!--       <span>Partenaire Officiel du</span> -->
      <%#= image_tag "wagonlogo.png", height: 50 %>
    <%# end %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", "/dashboard", class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Recherche", coders_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key , height: 40, weight: 40,
            class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dnpdonlro/image/upload/v1605793441/unknown_user_smsl6v.jpg", height: 40, weight: 40,
            class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <span class="dropdown-item">
              Bonjour <%= current_user.first_name %>
            </span>
            <%= link_to "Editer mon profil", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path(current_user), method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Créer votre compte", new_user_registration_path, class: "btn btn-outline-danger rounded-pill" %>
        </li>
         <li class="nav-item active">
          <%= link_to "Me connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>